In [1]:
from kaggle.api.kaggle_api_extended import KaggleApi

In [2]:
api = KaggleApi()
api.authenticate()

api.dataset_download_files(
    'rohanrao/formula-1-world-championship-1950-2020',
    path='./f1_datasets',
    unzip=True
)

Dataset URL: https://www.kaggle.com/datasets/rohanrao/formula-1-world-championship-1950-2020

In [3]:
import pandas as pd
import os
# Load the datasets

datasets = ['circuits', 'constructors', 'drivers', 'races', 'results']

dataframes = {}
for dataset in datasets:
    file_path = os.path.join('./f1_datasets', f'{dataset}.csv')
    dataframes[dataset] = pd.read_csv(file_path)

dataframes

{'circuits':     circuitId   circuitRef                                  name  \
 0           1  albert_park        Albert Park Grand Prix Circuit
 1           2       sepang          Sepang International Circuit
 2           3      bahrain         Bahrain International Circuit
 3           4    catalunya        Circuit de Barcelona-Catalunya
 4           5     istanbul                         Istanbul Park
 ..        ...          ...                                   ...
 72         75     portimao    Autódromo Internacional do Algarve
 73         76      mugello  Autodromo Internazionale del Mugello
 74         77       jeddah               Jeddah Corniche Circuit
 75         78       losail          Losail International Circuit
 76         79        miami         Miami International Autodrome

         location       country       lat        lng  alt  \
 0      Melbourne     Australia -37.84970  144.96800   10
 1   Kuala Lumpur      Malaysia   2.76083  101.73800   18
 2         Sakhir       Bahrain  26.03250   50.51060    7
 3       Montmeló         Spain  41.57000    2.26111  109
 4       Istanbul        Turkey  40.95170   29.40500  130
 ..           ...           ...       ...        ...  ...
 72      Portimão      Portugal  37.22700   -8.62670  108
 73       Mugello         Italy  43.99750   11.37190  255
 74        Jeddah  Saudi Arabia  21.63190   39.10440   15
 75     Al Daayen         Qatar  25.49000   51.45420   12
 76         Miami           USA  25.95810  -80.23890    0

                                                   url
 0   http://en.wikipedia.org/wiki/Melbourne_Grand_P...
 1   http://en.wikipedia.org/wiki/Sepang_Internatio...
 2   http://en.wikipedia.org/wiki/Bahrain_Internati...
 3   http://en.wikipedia.org/wiki/Circuit_de_Barcel...
 4          http://en.wikipedia.org/wiki/Istanbul_Park
 ..                                                ...
 72  http://en.wikipedia.org/wiki/Algarve_Internati...
 73       http://en.wikipedia.org/wiki/Mugello_Circuit
 74  http://en.wikipedia.org/wiki/Jeddah_Street_Cir...
 75  http://en.wikipedia.org/wiki/Losail_Internatio...
 76  http://en.wikipedia.org/wiki/Miami_Internation...

 [77 rows x 9 columns],
 'constructors':      constructorId constructorRef            name nationality  \
 0                1        mclaren         McLaren     British
 1                2     bmw_sauber      BMW Sauber      German
 2                3       williams        Williams     British
 3                4        renault         Renault      French
 4                5     toro_rosso      Toro Rosso     Italian
 ..             ...            ...             ...         ...
 207            210           haas    Haas F1 Team    American
 208            211   racing_point    Racing Point     British
 209            213     alphatauri      AlphaTauri     Italian
 210            214         alpine  Alpine F1 Team      French
 211            215             rb      RB F1 Team     Italian

                                                    url
 0                 http://en.wikipedia.org/wiki/McLaren
 1              http://en.wikipedia.org/wiki/BMW_Sauber
 2    http://en.wikipedia.org/wiki/Williams_Grand_Pr...
 3    http://en.wikipedia.org/wiki/Renault_in_Formul...
 4     http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
 ..                                                 ...
 207          http://en.wikipedia.org/wiki/Haas_F1_Team
 208  http://en.wikipedia.org/wiki/Racing_Point_F1_Team
 209   http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
 210        http://en.wikipedia.org/wiki/Alpine_F1_Team
 211   http://en.wikipedia.org/wiki/RB_Formula_One_Team

 [212 rows x 5 columns],
 'drivers':      driverId   driverRef number code  forename     surname         dob  \
 0           1    hamilton     44  HAM     Lewis    Hamilton  1985-01-07
 1           2    heidfeld     \N  HEI      Nick    Heidfeld  1977-05-10
 2           3     rosberg      6  ROS      Nico     Rosberg  1985-06-27
 3           4      alonso     14  ALO  Fernando      Alonso  1981-07-29
 4           5  kovalainen     \N  KOV    Heikki  Kovalainen  1981-10-19
 ..        ...         ...    ...  ...       ...         ...         ...
 856       858    sargeant      2  SAR     Logan    Sargeant  2000-12-31
 857       859      lawson     30  LAW      Liam      Lawson  2002-02-11
 858       860     bearman     38  BEA    Oliver     Bearman  2005-05-08
 859       861   colapinto     43  COL    Franco   Colapinto  2003-05-27
 860       862      doohan     61  DOO      Jack      Doohan  2003-01-20

        nationality                                             url
 0          British     http://en.wikipedia.org/wiki/Lewis_Hamilton
 1           German      http://en.wikipedia.org/wiki/Nick_Heidfeld
 2           German       http://en.wikipedia.org/wiki/Nico_Rosberg
 3          Spanish    http://en.wikipedia.org/wiki/Fernando_Alonso
 4          Finnish  http://en.wikipedia.org/wiki/Heikki_Kovalainen
 ..             ...                                             ...
 856       American     http://en.wikipedia.org/wiki/Logan_Sargeant
 857  New Zealander        http://en.wikipedia.org/wiki/Liam_Lawson
 858        British     http://en.wikipedia.org/wiki/Oliver_Bearman
 859   Argentinian    http://en.wikipedia.org/wiki/Franco_Colapinto
 860     Australian        http://en.wikipedia.org/wiki/Jack_Doohan

 [861 rows x 9 columns],
 'races':       raceId  year  round  circuitId                    name        date  \
 0          1  2009      1          1   Australian Grand Prix  2009-03-29
 1          2  2009      2          2    Malaysian Grand Prix  2009-04-05
 2          3  2009      3         17      Chinese Grand Prix  2009-04-19
 3          4  2009      4          3      Bahrain Grand Prix  2009-04-26
 4          5  2009      5          4      Spanish Grand Prix  2009-05-10
 ...      ...   ...    ...        ...                     ...         ...
 1120    1140  2024     20         32  Mexico City Grand Prix  2024-10-27
 1121    1141  2024     21         18    São Paulo Grand Prix  2024-11-03
 1122    1142  2024     22         80    Las Vegas Grand Prix  2024-11-23
 1123    1143  2024     23         78        Qatar Grand Prix  2024-12-01
 1124    1144  2024     24         24    Abu Dhabi Grand Prix  2024-12-08

           time                                                url    fp1_date  \
 0     06:00:00  http://en.wikipedia.org/wiki/2009_Australian_G...          \N
 1     09:00:00  http://en.wikipedia.org/wiki/2009_Malaysian_Gr...          \N
 2     07:00:00  http://en.wikipedia.org/wiki/2009_Chinese_Gran...          \N
 3     12:00:00  http://en.wikipedia.org/wiki/2009_Bahrain_Gran...          \N
 4     12:00:00  http://en.wikipedia.org/wiki/2009_Spanish_Gran...          \N
 ...        ...                                                ...         ...
 1120  20:00:00  https://en.wikipedia.org/wiki/2024_Mexico_City...  2024-10-25
 1121  17:00:00  https://en.wikipedia.org/wiki/2024_S%C3%A3o_Pa...  2024-11-01
 1122  06:00:00  https://en.wikipedia.org/wiki/2024_Las_Vegas_G...  2024-11-21
 1123  17:00:00  https://en.wikipedia.org/wiki/2024_Qatar_Grand...  2024-11-29
 1124  13:00:00  https://en.wikipedia.org/wiki/2024_Abu_Dhabi_G...  2024-12-06

       fp1_time    fp2_date  fp2_time    fp3_date  fp3_time  quali_date  \
 0           \N          \N        \N          \N        \N          \N
 1           \N          \N        \N          \N        \N          \N
 2           \N          \N        \N          \N        \N          \N
 3           \N          \N        \N          \N        \N          \N
 4           \N          \N        \N          \N        \N          \N
 ...        ...         ...       ...         ...       ...         ...
 1120  18:30:00  2024-10-25  22:00:00  2024-10-26  17:30:00  2024-10-26
 1121  14:30:00  2024-11-01  18:30:00          \N        \N  2024-11-02
 1122  02:30:00  2024-11-21  06:00:00  2024-11-22  02:30:00  2024-11-22
 1123  13:30:00  2024-11-29  17:30:00          \N        \N  2024-11-30
 1124  09:30:00  2024-12-06  13:00:00  2024-12-07  10:30:00  2024-12-07

      quali_time sprint_date sprint_time
 0            \N          \N          \N
 1            \N          \N          \N
 2            \N          \N          \N
 3            \N          \N          \N
 4            \N          \N          \N
 ...         ...         ...         ...
 1120   21:00:00          \N          \N
 1121   18:00:00  2024-11-02    14:00:00
 1122   06:00:00          \N          \N
 1123   17:00:00  2024-11-30    13:00:00
 1124   14:00:00          \N          \N

 [1125 rows x 18 columns],
 'results':        resultId  raceId  driverId  constructorId number  grid position  \
 0             1      18         1              1     22     1        1
 1             2      18         2              2      3     5        2
 2             3      18         3              3      7     7        3
 3             4      18         4              4      5    11        4
 4             5      18         5              1     23     3        5
 ...         ...     ...       ...            ...    ...   ...      ...
 26754     26760    1144       825            210     20    14       16
 26755     26761    1144       859            215     30    12       17
 26756     26762    1144       822             15     77     9       \N
 26757     26763    1144       861              3     43    20       \N
 26758     26764    1144       815              9     11    10       \N

       positionText  positionOrder  points  laps         time milliseconds  \
 0                1              1    10.0    58  1:34:50.616      5690616
 1                2              2     8.0    58       +5.478      5696094
 2                3              3     6.0    58       +8.163      5698779
 3                4              4     5.0    58      +17.181      5707797
 4                5              5     4.0    58      +18.014      5708630
 ...            ...            ...     ...   ...          ...          ...
 26754           16             16     0.0    57           \N           \N
 26755           17             17     0.0    55           \N           \N
 26756            R             18     0.0    30           \N           \N
 26757            R             19     0.0    26           \N           \N
 26758            R             20     0.0     0           \N           \N

       fastestLap rank fastestLapTime fastestLapSpeed  statusId
 0             39    2       1:27.452         218.300         1
 1             41    3       1:27.739         217.586         1
 2             41    5       1:28.090         216.719         1
 3             58    7       1:28.603         215.464         1
 4             43    1       1:27.418         218.385         1
 ...          ...  ...            ...             ...       ...
 26754         57    1       1:25.637         222.002        11
 26755         52   12       1:28.751         214.212         5
 26756         14   19       1:29.482         212.462       130
 26757          5   17       1:29.411         212.631         5
 26758         \N    0             \N              \N         4

 [26759 rows x 18 columns]}

In [4]:
dataframes['races'].columns, dataframes['results'].columns, dataframes['constructors'].columns, dataframes['circuits'].columns, dataframes['drivers'].columns

(Index(['raceId', 'year', 'round', 'circuitId', 'name', 'date', 'time', 'url',
        'fp1_date', 'fp1_time', 'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time',
        'quali_date', 'quali_time', 'sprint_date', 'sprint_time'],
       dtype='object'),
 Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid',
        'position', 'positionText', 'positionOrder', 'points', 'laps', 'time',
        'milliseconds', 'fastestLap', 'rank', 'fastestLapTime',
        'fastestLapSpeed', 'statusId'],
       dtype='object'),
 Index(['constructorId', 'constructorRef', 'name', 'nationality', 'url'], dtype='object'),
 Index(['circuitId', 'circuitRef', 'name', 'location', 'country', 'lat', 'lng',
        'alt', 'url'],
       dtype='object'),
 Index(['driverId', 'driverRef', 'number', 'code', 'forename', 'surname', 'dob',
        'nationality', 'url'],
       dtype='object'))

In [5]:
dataframes['races'].drop(columns=['url', 'round', 'fp1_date', 'fp1_time', 'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time',
        'quali_date', 'quali_time', 'sprint_date', 'sprint_time', 'time'], inplace=True)
dataframes['races'].rename(columns={'name': 'GP name'}, inplace=True)
dataframes['constructors'].drop(columns=['constructorRef', 'url'], inplace=True)
dataframes['constructors'].rename(columns={'name': 'team', 'nationality': 'team_home'}, inplace=True)
dataframes['drivers'].drop(columns=['forename', 'surname', 'code', 'number', 'url'], inplace=True)
dataframes['drivers'].rename(columns={'name': 'driver', 'nationality': 'driver_home'}, inplace=True)
dataframes['results'].drop(columns=['positionText', 'points', 'laps', 'time', 'milliseconds', 'positionOrder', 'fastestLapTime',
                                    'fastestLapSpeed', 'rank', 'laps', 'time', 'number'], inplace=True)
dataframes['results'].rename(columns={'position': 'finish', 'grid': 'start'}, inplace=True)
dataframes['circuits'].drop(columns=['circuitRef', 'url', 'lat', 'lng', 'alt'], inplace=True)
dataframes['circuits'].rename(columns={'name': 'circuit name'}, inplace=True)

In [6]:
f1_data = dataframes['races'].merge(
    dataframes['results'], on='raceId', how='left'
    ).merge(
        dataframes['constructors'], on='constructorId', how='left'
    ).merge(
        dataframes['drivers'], on='driverId', how='left'
    ).merge(
        dataframes['circuits'], on='circuitId', how='left'
        )

In [7]:
f1_data = f1_data[f1_data['year'] >= 2012]
f1_data.shape

(5524, 20)

In [8]:
f1_data['date'] = pd.to_datetime(f1_data['date'])
f1_data['dob'] = pd.to_datetime(f1_data['dob'])

In [9]:
f1_data.columns

Index(['raceId', 'year', 'circuitId', 'GP name', 'date', 'resultId',
       'driverId', 'constructorId', 'start', 'finish', 'fastestLap',
       'statusId', 'team', 'team_home', 'driverRef', 'dob', 'driver_home',
       'circuit name', 'location', 'country'],
      dtype='object')

In [10]:
f1_data.drop(columns=['resultId', 'constructorId', 'fastestLap', 'driverId', 'circuitId', 'raceId'], inplace=True)
f1_data.shape

(5524, 14)

In [11]:
f1_data

,year,GP name,date,start,finish,statusId,team,team_home,driverRef,dob,driver_home,circuit name,location,country
21235,2012,Australian Grand Prix,2012-03-18,2,1,1,McLaren,British,button,1980-01-19,British,Albert Park Grand Prix Circuit,Melbourne,Australia
21236,2012,Australian Grand Prix,2012-03-18,6,2,1,Red Bull,Austrian,vettel,1987-07-03,German,Albert Park Grand Prix Circuit,Melbourne,Australia
21237,2012,Australian Grand Prix,2012-03-18,1,3,1,McLaren,British,hamilton,1985-01-07,British,Albert Park Grand Prix Circuit,Melbourne,Australia
21238,2012,Australian Grand Prix,2012-03-18,5,4,1,Red Bull,Austrian,webber,1976-08-27,Australian,Albert Park Grand Prix Circuit,Melbourne,Australia
21239,2012,Australian Grand Prix,2012-03-18,12,5,1,Ferrari,Italian,alonso,1981-07-29,Spanish,Albert Park Grand Prix Circuit,Melbourne,Australia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,2024,Abu Dhabi Grand Prix,2024-12-08,14,16,11,Haas F1 Team,American,kevin_magnussen,1992-10-05,Danish,Yas Marina Circuit,Abu Dhabi,UAE
26755,2024,Abu Dhabi Grand Prix,2024-12-08,12,17,5,RB F1 Team,Italian,lawson,2002-02-11,New Zealander,Yas Marina Circuit,Abu Dhabi,UAE
26756,2024,Abu Dhabi Grand Prix,2024-12-08,9,\N,130,Sauber,Swiss,bottas,1989-08-28,Finnish,Yas Marina Circuit,Abu Dhabi,UAE
26757,2024,Abu Dhabi Grand Prix,2024-12-08,20,\N,5,Williams,British,colapinto,2003-05-27,Argentinian,Yas Marina Circuit,Abu Dhabi,UAE
26758,2024,Abu Dhabi Grand Prix,2024-12-08,10,\N,4,Red Bull,Austrian,perez,1990-01-26,Mexican,Yas Marina Circuit,Abu Dhabi,UAE

In [12]:
print(f1_data['team_home'].unique())
print(f1_data['driver_home'].unique())
print(f1_data['country'].unique())

['British' 'Austrian' 'Italian' 'Swiss' 'Indian' 'German' 'Russian'
 'Malaysian' 'Spanish' 'American' 'French']
['British' 'German' 'Australian' 'Spanish' 'Japanese' 'Finnish' 'Mexican'
 'French' 'Venezuelan' 'Brazilian' 'Russian' 'Indian' 'Belgian' 'Dutch'
 'Danish' 'Swedish' 'American' 'Indonesian' 'Italian' 'Canadian'
 'New Zealander' 'Monegasque' 'Thai' 'Polish' 'Chinese' 'Argentinian ']
['Australia' 'Malaysia' 'China' 'Bahrain' 'Spain' 'Monaco' 'Canada' 'UK'
 'Germany' 'Hungary' 'Belgium' 'Italy' 'Singapore' 'Japan' 'Korea' 'India'
 'UAE' 'USA' 'Brazil' 'Austria' 'Russia' 'Mexico' 'Azerbaijan' 'France'
 'Portugal' 'Turkey' 'Qatar' 'Netherlands' 'Saudi Arabia' 'United States']

In [13]:
def nationality(x):
    x = str(x).strip().lower()
    if x in ['austrian', 'austria']:
        return 'AUT'
    if x in ['australian', 'australia']:
        return 'AUS'
    if x in ['indian', 'india']:
        return 'IND'
    if x in ['indonesian', 'indonesia']:
        return 'INA'
    if x in ['uk', 'british', 'england', 'great britain']:
        return 'BRI'
    if x in ['usa', 'united states', 'american']:
        return 'AME'
    if x in ['fra', 'france', 'french']:
        return 'FRE'
    return x[:3].upper()

f1_data['driver_home'] = f1_data['driver_home'].apply(nationality)
f1_data['team_home'] = f1_data['team_home'].apply(nationality)
f1_data['country'] = f1_data['country'].apply(nationality)

f1_data['driver home'] = (f1_data['driver_home'] == f1_data['country']).astype(int)
f1_data['team home'] = (f1_data['team_home'] == f1_data['country']).astype(int)

In [14]:
print(f1_data['driver home'].unique())
print(f1_data['team home'].unique())
f1_data = f1_data.drop(columns=['driver_home', 'team_home'])
f1_data

[0 1]
[0 1]

,year,GP name,date,start,finish,statusId,team,driverRef,dob,circuit name,location,country,driver home,team home
21235,2012,Australian Grand Prix,2012-03-18,2,1,1,McLaren,button,1980-01-19,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
21236,2012,Australian Grand Prix,2012-03-18,6,2,1,Red Bull,vettel,1987-07-03,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
21237,2012,Australian Grand Prix,2012-03-18,1,3,1,McLaren,hamilton,1985-01-07,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
21238,2012,Australian Grand Prix,2012-03-18,5,4,1,Red Bull,webber,1976-08-27,Albert Park Grand Prix Circuit,Melbourne,AUS,1,0
21239,2012,Australian Grand Prix,2012-03-18,12,5,1,Ferrari,alonso,1981-07-29,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,2024,Abu Dhabi Grand Prix,2024-12-08,14,16,11,Haas F1 Team,kevin_magnussen,1992-10-05,Yas Marina Circuit,Abu Dhabi,UAE,0,0
26755,2024,Abu Dhabi Grand Prix,2024-12-08,12,17,5,RB F1 Team,lawson,2002-02-11,Yas Marina Circuit,Abu Dhabi,UAE,0,0
26756,2024,Abu Dhabi Grand Prix,2024-12-08,9,\N,130,Sauber,bottas,1989-08-28,Yas Marina Circuit,Abu Dhabi,UAE,0,0
26757,2024,Abu Dhabi Grand Prix,2024-12-08,20,\N,5,Williams,colapinto,2003-05-27,Yas Marina Circuit,Abu Dhabi,UAE,0,0
26758,2024,Abu Dhabi Grand Prix,2024-12-08,10,\N,4,Red Bull,perez,1990-01-26,Yas Marina Circuit,Abu Dhabi,UAE,0,0

In [ ]:
f1_data = f1_data.reset_index(drop=True)
f1_data

,year,GP name,date,start,finish,statusId,team,driverRef,dob,circuit name,location,country,driver home,team home
0,2012,Australian Grand Prix,2012-03-18,2,1,1,McLaren,button,1980-01-19,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
1,2012,Australian Grand Prix,2012-03-18,6,2,1,Red Bull,vettel,1987-07-03,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
2,2012,Australian Grand Prix,2012-03-18,1,3,1,McLaren,hamilton,1985-01-07,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
3,2012,Australian Grand Prix,2012-03-18,5,4,1,Red Bull,webber,1976-08-27,Albert Park Grand Prix Circuit,Melbourne,AUS,1,0
4,2012,Australian Grand Prix,2012-03-18,12,5,1,Ferrari,alonso,1981-07-29,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5519,2024,Abu Dhabi Grand Prix,2024-12-08,14,16,11,Haas F1 Team,kevin_magnussen,1992-10-05,Yas Marina Circuit,Abu Dhabi,UAE,0,0
5520,2024,Abu Dhabi Grand Prix,2024-12-08,12,17,5,RB F1 Team,lawson,2002-02-11,Yas Marina Circuit,Abu Dhabi,UAE,0,0
5521,2024,Abu Dhabi Grand Prix,2024-12-08,9,\N,130,Sauber,bottas,1989-08-28,Yas Marina Circuit,Abu Dhabi,UAE,0,0
5522,2024,Abu Dhabi Grand Prix,2024-12-08,20,\N,5,Williams,colapinto,2003-05-27,Yas Marina Circuit,Abu Dhabi,UAE,0,0
5523,2024,Abu Dhabi Grand Prix,2024-12-08,10,\N,4,Red Bull,perez,1990-01-26,Yas Marina Circuit,Abu Dhabi,UAE,0,0

In [17]:
missing = f1_data[f1_data['dob'].isna()]
missing['driverRef'].unique()

array([], dtype=object)

In [18]:
season2025 = pd.read_csv('./datasets/season2025_results.csv')

In [19]:
f1_data = pd.concat([f1_data, season2025])
f1_data.reset_index(drop=True)
f1_data

,year,GP name,date,start,finish,statusId,team,driverRef,dob,circuit name,location,country,driver home,team home
21235,2012,Australian Grand Prix,2012-03-18 00:00:00,2,1,1,McLaren,button,1980-01-19 00:00:00,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
21236,2012,Australian Grand Prix,2012-03-18 00:00:00,6,2,1,Red Bull,vettel,1987-07-03 00:00:00,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
21237,2012,Australian Grand Prix,2012-03-18 00:00:00,1,3,1,McLaren,hamilton,1985-01-07 00:00:00,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
21238,2012,Australian Grand Prix,2012-03-18 00:00:00,5,4,1,Red Bull,webber,1976-08-27 00:00:00,Albert Park Grand Prix Circuit,Melbourne,AUS,1,0
21239,2012,Australian Grand Prix,2012-03-18 00:00:00,12,5,1,Ferrari,alonso,1981-07-29 00:00:00,Albert Park Grand Prix Circuit,Melbourne,AUS,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,2025,Austrian Grand Prix,2025-06-29,18,16,1,Red Bull,tsunoda,2000-05-11,Red Bull Ring,Spielberg,AUT,0,1
234,2025,Austrian Grand Prix,2025-06-29,12,17,3,Williams,albon,1996-03-23,Red Bull Ring,Spielberg,AUT,0,0
235,2025,Austrian Grand Prix,2025-06-29,7,18,3,Red Bull,max_verstappen,1997-09-30,Red Bull Ring,Spielberg,AUT,0,1
236,2025,Austrian Grand Prix,2025-06-29,9,19,3,Mercedes,antonelli,NaN,Red Bull Ring,Spielberg,AUT,0,0
237,2025,Austrian Grand Prix,2025-06-29,19,20,3,Williams,sainz,1994-09-01,Red Bull Ring,Spielberg,AUT,0,0

In [20]:
f1_data = f1_data.rename(columns={
    'driverRef': 'driver',
})

In [21]:
f1_data['driver_dnf'] = f1_data['statusId'].apply(lambda x: 1 if x in [3,4,20,29,31,41,68,73,81,97,82,104,107,130,137] else 0)
f1_data['constructor_dnf'] = f1_data['statusId'].apply(lambda x: 1 if x not in [3,4,20,29,31,41,68,73,81,97,82,104,107,130,137,1] else 0)

In [22]:
missing = f1_data[f1_data['dob'].isna()]
missing['driver'].unique()

array(['antonelli', 'bortoleto', 'hadjar'], dtype=object)

In [24]:
manual_dobs = {
    'bortoleto': '2004-10-14',
    'hadjar'   : '2004-09-28',
    'antonelli': '2006-08-25'
}

for ref, date_str in manual_dobs.items():
    f1_data.loc[
        (f1_data['driver'] == ref) & (f1_data['dob'].isna()),
        'dob'
    ] = pd.to_datetime(date_str)

In [35]:
f1_data['date'] = pd.to_datetime(f1_data['date'])
f1_data['dob'] = pd.to_datetime(f1_data['dob'])
f1_data.dtypes

year                        int64
GP name                    object
date               datetime64[ns]
start                       int64
finish                     object
statusId                    int64
team                       object
driver                     object
dob                datetime64[ns]
circuit name               object
location                   object
country                    object
driver home                 int64
team home                   int64
driver_dnf                  int64
constructor_dnf             int64
dtype: object

In [36]:
f1_data['age_at_gp_in_days'] = abs(f1_data['dob']-f1_data['date'])
f1_data['age_at_gp_in_days'] = f1_data['age_at_gp_in_days'].apply(lambda x: str(x).split(' ')[0])

In [37]:
f1_data['team'].unique()

array(['McLaren', 'Red Bull', 'Ferrari', 'Sauber', 'Lotus F1',
       'Toro Rosso', 'Force India', 'Mercedes', 'Williams', 'Marussia',
       'Caterham', 'HRT', 'Manor Marussia', 'Haas F1 Team', 'Renault',
       'Alfa Romeo', 'Racing Point', 'AlphaTauri', 'Aston Martin',
       'Alpine F1 Team', 'RB F1 Team', 'Alpine'], dtype=object)

In [38]:
f1_data['team'] = f1_data['team'].apply(lambda x: 'Aston Martin' if x=='Force India' else x)
f1_data['team'] = f1_data['team'].apply(lambda x: 'Aston Martin' if x=='Racing Point' else x)
f1_data['team'] = f1_data['team'].apply(lambda x: 'Sauber' if x=='Alfa Romeo' else x)
f1_data['team'] = f1_data['team'].apply(lambda x: 'Renault' if x=='Lotus F1' else x)
f1_data['constructor'] = f1_data['team'].apply(lambda x: 'Renault' if x=='Alpine' else x)
f1_data['team'] = f1_data['team'].apply(lambda x: 'AlphaTauri' if x=='Toro Rosso' else x)

In [ ]:
dnf_by_driver = f1_data.groupby('driver').sum()['driver_dnf']
driver_race_entered = f1_data.groupby('driver').count()['driver_dnf']
driver_dnf_ratio = (dnf_by_driver/driver_race_entered)
driver_confidence = 1-driver_dnf_ratio
driver_confidence_dict = dict(zip(driver_confidence.index,driver_confidence))


dnf_by_constructor = f1_data.groupby('team').sum()['constructor_dnf']
constructor_race_entered = f1_data.groupby('team').count()['constructor_dnf']
constructor_dnf_ratio = (dnf_by_constructor/constructor_race_entered)
constructor_relaiblity = 1-constructor_dnf_ratio
constructor_relaiblity_dict = dict(zip(constructor_relaiblity.index,constructor_relaiblity))